services:
  visionvault:
    image: asatyr2024/mythosmachina:visionvault
    ports:
      - '3000:3000'
    volumes:
      - ./public/images:/app/public/images
      - ./data:/app/data
      - ./nsfw.txt:/app/config/nsfw.txt
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/visionvault.db
    command: >
      sh -c "ln -sf /app/config/nsfw.txt /app/nsfw.txt && npm start"
